services:

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8003:8003"
    volumes:
      - ./gateway:/app
    networks:
      - my-network
    depends_on:
      - auth-service

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8000:8000"
    volumes:
      - ./auth:/app
      - auth_db:/app/data
    networks:
      - my-network
  
  lms-service:
    build: ./lms
    container_name: lms-service
    ports:
      - "8001:8001"
    volumes:
      - ./lms:/app
      - lms_db:/app/data
      - ./lms_service/media:/app/media:rw,z
    networks:
      - my-network
    depends_on:
      - auth-service
  
  avaliacao-service:
    build: ./avaliacao
    container_name: avaliacao-service
    ports:
      - "8002:8002"
    volumes:
      - ./avaliacao:/app
      - avaliacao_db:/app/data
      - ./avaliacao_service/media:/app/media:rw,z
    networks:
      - my-network
    depends_on:
      - auth-service
      - lms-service

volumes:
  auth_db:
  lms_db:
  avaliacao_db:

networks:
  my-network:
    driver: bridge
