# Generated by Django 5.1.6 on 2025-04-05 00:10

import avaliacao_service.models.avaliacao_atividade
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.IntegerField()),
                ('atividade', models.IntegerField()),
                ('conteudo_para_avaliacao', models.FileField(upload_to=avaliacao_service.models.avaliacao_atividade.conteudo_para_avaliacao_path)),
                ('nota', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avaliação de Atividade',
                'verbose_name_plural': 'Avaliações de Atividades',
                'db_table': 'avaliacao_atividade',
                'ordering': ['atividade', 'aluno'],
            },
        ),
    ]
