# Generated by Django 5.1.6 on 2025-04-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoatividade',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
