# Generated by Django 5.1.6 on 2025-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
