# Generated by Django 5.1.6 on 2025-03-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0002_curso_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='created_by',
        ),
    ]
