# Generated by Django 5.1.6 on 2025-03-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0003_remove_curso_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='atividade',
        ),
    ]
