# Generated by Django 5.1.6 on 2025-04-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0004_remove_aula_atividade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['data_aula'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AddField(
            model_name='aula',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aulas', to='lms_service.atividade'),
        ),
        migrations.AddField(
            model_name='aula',
            name='data_aula',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='lms_service.turma'),
        ),
    ]
