# Generated by Django 5.1.6 on 2025-04-01 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0005_alter_aula_options_aula_atividade_aula_data_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='lms_service.turma'),
        ),
    ]
