# Generated by Django 5.1.6 on 2025-05-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_service', '0006_alter_aula_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='materia',
        ),
    ]
