# Generated by Django 5.1.6 on 2025-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='turmas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
